services:
  mysql:
    image: mysql:8.0.43
    container_name: cnf
    networks:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: default
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./my32gb.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/var/lib/mysql

networks:
  database: